trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'KubernetesServiceConnection'
    kubernetesServiceEndpoint: '<k8s-service-endpoint>'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'charts/AlphabetChecker-deployment.yml'
