apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphabet-checker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alphabet-checker
  template:
    metadata:
      labels:
        app: alphabet-checker
    spec:
      containers:
      - name: alphabet-checker
        image: ecr-repo-url/alphabetchecker:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: alphabet-checker-service
spec:
  type: LoadBalancer
  selector:
    app: alphabet-checker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
